### PR TITLE
Add support for Visual Studio 2022

### PR DESCRIPTION
**Pull request by A-23187**

### CODE REVIEW

**Comment by srbala** [comment]
@A-23187 Possible duplicate issue #98 and PR #99

**Comment by pkking** [comment]
need this PR, any maintainers can have a look?

**Review by benhillis — APPROVED** [review]

**Comment by GONNAGITU72** [comment]
```c++
/Start
```

**Comment by GONNAGITU72** [comment]
[](url)

**Review by Zionsammy — COMMENTED** [review]
Thanks

**Pull request merged**
